### ISSUE TITLE
Run updated code via the readme

### ISSUE THREAD

**Issue by hanselopolis** [SocketCAN-Capstone-Fall-2022/socketCAN-UM-Capstone-Fall-2022#13]
1) Clone repo for new code

2) First compile a linux-5.19.7 kernel using the provided config file (place it in the linux kernel source dir as .config). 

3) To create the initird make rootfs should build fuzzcan, place it in the initramfs and then create a new initramfs at the current directory.

4) Run qemu with:
qemu-system-x86_64 -kernel /path/to/bzImage -initrd /path/tofuzzcan-initramfs.cpio.gz
-append "root=/dev/ram0 rootfstype=ramfs init=/init console=ttyS0" -net nic,model=rtl8139
-net user -m 2048M --nographic

5) run fuzzcan with: /bin/fuzzcan -r

6) user readable output: cat outputfile | addr2line -e /path/to/vmlinux

**Comment by Shami-git** [comment]
![image](https://user-images.githubusercontent.com/22306262/196821561-5a937230-5994-425a-8405-6d955e13369f.png)

**Comment by hanselopolis** [comment]
I ran into a problem with getting the pointer values when running fuzzcan in qemu - points back to a script needing to be run before building the kernel. Corrected and added to the readme.
