### ISSUE TITLE
Debug mkrootfs.sh directory issue

### ISSUE THREAD

**Issue by hanselopolis** [SocketCAN-Capstone-Fall-2022/socketCAN-UM-Capstone-Fall-2022#14]
Currently, a number of junk directories are created when running the make rootfs command. Needs to be debugged.

ETA: also need to add kmsg device creation to mkrootfs script, qemu cannot find when trying to run fuzzcan

**Comment by hanselopolis** [comment]
@maxhagemann took point on the fix, @hanselopolis updated mkrootfs.sh and pushed to repo

**Comment by Shami-git** [comment]
mkrootfs.sh updates work well after points have been fixed
