### ISSUE TITLE
Update fuzzcan makefile

### ISSUE THREAD

**Issue by hanselopolis** [SocketCAN-Capstone-Fall-2022/socketCAN-UM-Capstone-Fall-2022#16]
Update makefile for fuzzcan -

Move output from bin to working dir
Copy fuzzcan to rootfs/bin/
Add clean up

**Comment by hanselopolis** [comment]
Update made to makefile, pushed to repo

**Comment by Shami-git** [comment]
Got updated makefile and ran well
